# Generated by Django 5.0.6 on 2024-05-18 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.module'),
        ),
        migrations.AddField(
            model_name='participant',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.task'),
        ),
    ]
