# Generated by Django 5.0.6 on 2024-05-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_participant_module_alter_participant_task_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='modules',
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
