# Generated by Django 5.0.6 on 2024-05-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_module_table_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='module',
            table='main_module',
        ),
    ]
